# Generated by Django 4.1.1 on 2022-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolls',
            name='type',
            field=models.CharField(choices=[('I', 'Интерьерная кукла'), ('G', 'Игровая кукла'), ('D', 'Игрушка'), ('A', 'Одежда для куклы'), ('B', 'Одежда для игрушки')], max_length=30),
        ),
    ]
