# Generated by Django 4.1.1 on 2022-09-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_app', '0003_alter_dolls_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolls',
            name='type',
            field=models.CharField(choices=[('Интерьерные куколки', 'Интерьерная кукла'), ('Игровые куколки', 'Игровая кукла'), ('Игрушки', 'Игрушка'), ('Одежда для кукол', 'Одежда для куклы'), ('Одежда для игрушек', 'Одежда для игрушки')], max_length=30),
        ),
    ]
