# Generated by Django 4.1.1 on 2022-09-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_app', '0004_alter_dolls_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Феечка', 'Феечка'), ('Лисичка', 'Лисичка'), ('Санта', 'Санта')], max_length=50)),
                ('img', models.FileField(upload_to='static/photo/')),
            ],
        ),
    ]
