# Generated by Django 4.1.1 on 2022-09-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_app', '0006_alter_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('Феечка', 'Феечка'), ('Лисичка', 'Лисичка'), ('Санта', 'Санта')], max_length=50),
        ),
    ]
