# Generated by Django 4.1.1 on 2022-09-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doll_app', '0007_alter_photo_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
