# Generated by Django 4.1.1 on 2022-09-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doll_app', '0009_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('Коровка', 'Коровка'), ('Оленяша', 'Оленяша'), ('Лисичка', 'Лисичка'), ('Кудряшка', 'Кудряшка'), ('Гномик', 'Гномик'), ('Санта', 'Санта'), ('Ангелочек', 'Ангелочек'), ('Малышка', 'Малышка'), ('Бабочка', 'Бабочка'), ('Длинноножка', 'Длинноножка')], max_length=50),
        ),
    ]
